use anyhow::{Context, Result};
use colored::Colorize;
use std::fs;
use std::path::Path;

use crate::cli::args::InitArgs;
use crate::runner;

const STARTER_CONFIG_YAML: &str = r#"# Argus Project Configuration
# Generated by `argus init`
version: 1
project: "my-project"

# Specification Document (SFD) settings
sfd:
  dir: ".argus/context/sfd"
  # active: "feature-spec.md"

# Model tier mappings for cost and reasoning optimization
models:
  fast: "google/gemini-2.5-flash"
  standard: "anthropic/claude-3-7-sonnet"
  deep: "anthropic/claude-3-7-sonnet:high"

# Squad definitions mapping squad name to persona names
squads:
  forms:
    - id-regulatory-sentinel
    - form-boundary-saboteur
    - cascade-dropdown-glitcher
  state:
    - stock-ledger-auditor
    - orphan-cascade-hunter
  sync:
    - payload-pessimist
    - sync-deadlock-guard
    - hardware-sensor-adversary
  spec:
    - sfd-clause-detective
    - rbac-identity-gatekeeper
  all:
    - sfd-clause-detective
    - id-regulatory-sentinel
    - rbac-identity-gatekeeper
    - form-boundary-saboteur
    - cascade-dropdown-glitcher
    - concurrency-double-tapper
    - stock-ledger-auditor
    - orphan-cascade-hunter
    - payload-pessimist
    - sync-deadlock-guard
    - hardware-sensor-adversary
"#;

const STARTER_ORACLES_YAML: &str = r#"# Argus Behavioral Oracles Registry
schemaVersion: 1
oracles:
  state.reversibility:
    kind: state-invariant
    rule: "Deleting an unpushed local transaction must emit a compensatory stock mutation"
    covers: [inventory, sales, storage]

  boundary.input-sanitization:
    kind: validation-contract
    rule: "Input fields must enforce digit-only filtering and explicit length limits"
    covers: [forms, ui, validation]

  sync.graceful-empty:
    kind: resilience-contract
    rule: "Operational download sync on HTTP 200 OK must fallback to empty list when payload is null"
    covers: [network, sync, download]
"#;

/// Executes the `argus init` command to scaffold the `.argus` directory structure.
pub async fn run(args: &InitArgs) -> Result<()> {
    let target = &args.target_dir;
    let argus_dir = target.join(".argus");

    println!(
        "{} {}",
        "Initializing Argus in".bold().cyan(),
        target.display().to_string().yellow()
    );

    // 1. Create directories
    let dirs_to_create = [
        argus_dir.clone(),
        argus_dir.join("personas"),
        argus_dir.join("context").join("sfd"),
        argus_dir.join("reports"),
    ];

    for dir in &dirs_to_create {
        if !dir.exists() {
            fs::create_dir_all(dir)
                .with_context(|| format!("Failed to create directory at '{}'", dir.display()))?;
            println!("  {} {}", "✔ Created directory:".green(), dir.display());
        }
    }

    // 2. Scaffold .argus/config.yaml
    let config_path = argus_dir.join("config.yaml");
    write_scaffold_file(
        &config_path,
        STARTER_CONFIG_YAML,
        args.force,
        "configuration",
    )?;

    // 3. Scaffold .argus/oracles.yaml
    let oracles_path = argus_dir.join("oracles.yaml");
    write_scaffold_file(
        &oracles_path,
        STARTER_ORACLES_YAML,
        args.force,
        "oracles registry",
    )?;

    // 4. If --auto is requested, spawn the Persona Architect subagent to profile the codebase
    if args.auto {
        auto_bootstrap_personas(target, &config_path).await?;
    }

    println!();
    println!(
        "{} Argus initialized successfully! Place your Markdown SFDs in '{}' and run '{}'.",
        "✓".bold().green(),
        argus_dir.join("context").join("sfd").display(),
        "argus audit".bold().cyan()
    );

    Ok(())
}

async fn auto_bootstrap_personas(target: &Path, config_path: &Path) -> Result<()> {
    println!();
    println!(
        "{} Profiling codebase with Persona Architect...",
        "⚙".bold().cyan()
    );

    let pb = indicatif::ProgressBar::new_spinner();
    pb.set_style(
        indicatif::ProgressStyle::default_spinner()
            .tick_chars("⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏ ")
            .template("{spinner:.cyan} {wide_msg}")
            .unwrap_or_else(|_| indicatif::ProgressStyle::default_spinner()),
    );
    pb.enable_steady_tick(std::time::Duration::from_millis(80));
    pb.set_message(
        "persona-architect: analyzing codebase and crafting tailored personas...".to_string(),
    );

    let pi_bin = std::env::var("ARGUS_PI_BIN").ok();
    let generated_files = match runner::bootstrap_tailored_personas(target, pi_bin.as_deref()).await
    {
        Ok(files) => {
            pb.finish_and_clear();
            files
        }
        Err(err) => {
            pb.finish_and_clear();
            eprintln!(
                "{} Failed to auto-generate tailored personas: {err:#}",
                "⚠".bold().yellow()
            );
            Vec::new()
        }
    };

    if generated_files.is_empty() {
        println!(
            "  {} No custom personas were generated (default personas remain available).",
            "!".yellow().bold()
        );
    } else {
        println!(
            "{} Persona Architect synthesized {} tailored persona(s):",
            "✔".bold().green(),
            generated_files.len().to_string().bold().cyan()
        );
        let mut persona_names = Vec::new();
        for file in &generated_files {
            let name = file
                .file_stem()
                .and_then(|s| s.to_str())
                .unwrap_or("unnamed");
            persona_names.push(name.to_string());
            println!(
                "  • {:<30} ({})",
                name.bold().green(),
                file.display().to_string().dimmed()
            );
        }

        // Register newly created personas under squad 'auto' in .argus/config.yaml
        if let Err(err) = append_auto_squad(config_path, &persona_names) {
            eprintln!(
                "  {} Failed to register auto squad in config: {err:#}",
                "⚠".bold().yellow()
            );
        } else {
            println!(
                "  {} Registered new squad '{}' in '{}'",
                "✔".bold().green(),
                "auto".cyan(),
                config_path.display().to_string().dimmed()
            );
        }
    }

    Ok(())
}

fn append_auto_squad(config_path: &Path, persona_names: &[String]) -> Result<()> {
    if !config_path.exists() {
        return Ok(());
    }
    let content = fs::read_to_string(config_path)
        .with_context(|| format!("Failed to read config file at '{}'", config_path.display()))?;

    let mut parsed: serde_yaml::Value = serde_yaml::from_str(&content)
        .with_context(|| format!("Failed to parse YAML config at '{}'", config_path.display()))?;

    if let Some(squads) = parsed.get_mut("squads").and_then(|s| s.as_mapping_mut()) {
        let auto_key = serde_yaml::Value::String("auto".to_string());
        let names_val = serde_yaml::Value::Sequence(
            persona_names
                .iter()
                .map(|n| serde_yaml::Value::String(n.clone()))
                .collect(),
        );
        squads.insert(auto_key, names_val);

        let updated_yaml = serde_yaml::to_string(&parsed)
            .with_context(|| "Failed to serialize updated config to YAML")?;
        fs::write(config_path, updated_yaml).with_context(|| {
            format!(
                "Failed to write updated config at '{}'",
                config_path.display()
            )
        })?;
    }

    Ok(())
}

fn write_scaffold_file(
    file_path: &Path,
    content: &str,
    force: bool,
    description: &str,
) -> Result<()> {
    if file_path.exists() && !force {
        println!(
            "  {} {} already exists at '{}' (skipping; use --force to overwrite)",
            "!".yellow().bold(),
            description,
            file_path.display()
        );
        return Ok(());
    }

    fs::write(file_path, content).with_context(|| {
        format!(
            "Failed to write {} at '{}'",
            description,
            file_path.display()
        )
    })?;

    println!("  {} {}", "✔ Generated:".green(), file_path.display());
    Ok(())
}
