use anyhow::{Context, Result};
use colored::Colorize;
use std::fs;
use std::path::Path;

use crate::cli::args::InitArgs;

const STARTER_CONFIG_YAML: &str = r#"# Argus Project Configuration
# Generated by `argus init`
version: 1
project: "my-project"

# Specification Document (SFD) settings
sfd:
  dir: ".argus/context/sfd"
  # active: "feature-spec.md"

# Model tier mappings for cost and reasoning optimization
models:
  fast: "google/gemini-2.5-flash"
  standard: "anthropic/claude-3-7-sonnet"
  deep: "anthropic/claude-3-7-sonnet:high"

# Squad definitions mapping squad name to persona names
squads:
  forms:
    - id-regulatory-sentinel
    - form-boundary-saboteur
    - cascade-dropdown-glitcher
  state:
    - stock-ledger-auditor
    - orphan-cascade-hunter
  sync:
    - payload-pessimist
    - sync-deadlock-guard
    - hardware-sensor-adversary
  spec:
    - sfd-clause-detective
    - rbac-identity-gatekeeper
  all:
    - sfd-clause-detective
    - id-regulatory-sentinel
    - rbac-identity-gatekeeper
    - form-boundary-saboteur
    - cascade-dropdown-glitcher
    - concurrency-double-tapper
    - stock-ledger-auditor
    - orphan-cascade-hunter
    - payload-pessimist
    - sync-deadlock-guard
    - hardware-sensor-adversary
"#;

const STARTER_ORACLES_YAML: &str = r#"# Argus Behavioral Oracles Registry
schemaVersion: 1
oracles:
  state.reversibility:
    kind: state-invariant
    rule: "Deleting an unpushed local transaction must emit a compensatory stock mutation"
    covers: [inventory, sales, storage]

  boundary.input-sanitization:
    kind: validation-contract
    rule: "Input fields must enforce digit-only filtering and explicit length limits"
    covers: [forms, ui, validation]

  sync.graceful-empty:
    kind: resilience-contract
    rule: "Operational download sync on HTTP 200 OK must fallback to empty list when payload is null"
    covers: [network, sync, download]
"#;

/// Executes the `argus init` command to scaffold the `.argus` directory structure.
pub fn run(args: &InitArgs) -> Result<()> {
    let target = &args.target_dir;
    let argus_dir = target.join(".argus");

    println!(
        "{} {}",
        "Initializing Argus in".bold().cyan(),
        target.display().to_string().yellow()
    );

    // 1. Create directories
    let dirs_to_create = [
        argus_dir.clone(),
        argus_dir.join("personas"),
        argus_dir.join("context").join("sfd"),
        argus_dir.join("reports"),
    ];

    for dir in &dirs_to_create {
        if !dir.exists() {
            fs::create_dir_all(dir)
                .with_context(|| format!("Failed to create directory at '{}'", dir.display()))?;
            println!("  {} {}", "✔ Created directory:".green(), dir.display());
        }
    }

    // 2. Scaffold .argus/config.yaml
    let config_path = argus_dir.join("config.yaml");
    write_scaffold_file(
        &config_path,
        STARTER_CONFIG_YAML,
        args.force,
        "configuration",
    )?;

    // 3. Scaffold .argus/oracles.yaml
    let oracles_path = argus_dir.join("oracles.yaml");
    write_scaffold_file(
        &oracles_path,
        STARTER_ORACLES_YAML,
        args.force,
        "oracles registry",
    )?;

    println!();
    println!(
        "{} Argus initialized successfully! Place your Markdown SFDs in '{}' and run '{}'.",
        "✓".bold().green(),
        argus_dir.join("context").join("sfd").display(),
        "argus audit".bold().cyan()
    );

    Ok(())
}

fn write_scaffold_file(
    file_path: &Path,
    content: &str,
    force: bool,
    description: &str,
) -> Result<()> {
    if file_path.exists() && !force {
        println!(
            "  {} {} already exists at '{}' (skipping; use --force to overwrite)",
            "!".yellow().bold(),
            description,
            file_path.display()
        );
        return Ok(());
    }

    fs::write(file_path, content).with_context(|| {
        format!(
            "Failed to write {} at '{}'",
            description,
            file_path.display()
        )
    })?;

    println!("  {} {}", "✔ Generated:".green(), file_path.display());
    Ok(())
}
